<?php

use ACFComposer\ACFComposer;
use Flynt\Components;

add_action('Flynt/afterRegisterComponents', function () {
    ACFComposer::registerFieldGroup([
        'name' => 'pageSecondaryNavigationComponents',
        'title' => 'Secondary Navigation Page Components',
        'style' => 'seamless',
        'fields' => [
            [
                'label' => 'Enable Secondary Navigation?',
                'name' => 'nav_enabled',
                'type' => 'true_false',
                'default_value' => 0,
                'ui' => 1,
            ],
            [
                'label' => 'Select Menu for Secondary Nav',
                'name' => 'menu_id',
                'type' => 'menu-chooser',
                'conditional_logic' => [
                    [
                        [
                            'fieldPath' => 'nav_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
            ],
            [
                'name' => 'pageSecondaryNavigationComponents',
                'label' => __('Secondary Navigation Page Components', 'flynt'),
                'type' => 'flexible_content',
                'button_label' => __('Add Component', 'flynt'),
                'layouts' => [
                    Components\AllNews\getACFLayout(),
                    Components\Awards\getACFLayout(),
                    Components\BigCards\getACFLayout(),
                    Components\Breadcrumb\getACFLayout(),
                    Components\CaseStudy\getACFLayout(),
                    Components\ChecklistCard\getACFLayout(),
                    Components\ClientLogos\getACFLayout(),
                    Components\ComplementaryFeatures\getACFLayout(),
                    Components\ContactUs\getACFLayout(),
                    Components\ContentCards\getACFLayout(),
                    Components\ContentLibraryCategories\getACFLayout(),
                    Components\ContentLibraryFeaturedPost\getACFLayout(),
                    Components\ContentLibraryHero\getACFLayout(),
                    Components\ContentLibrarySliders\getACFLayout(),
                    Components\EventsCards\getACFLayout(),
                    Components\FeaturedEvent\getACFLayout(),
                    Components\FeaturedPodcast\getACFLayout(),
                    Components\Form\getACFLayout(),
                    Components\G2Awards\getACFLayout(),
                    Components\GradientBackgroundSection\getACFLayout(),
                    Components\HomeClients\getACFLayout(),
                    Components\HomeOurPlatform\getACFLayout(),
                    Components\HomepageHero\getACFLayout(),
                    Components\HomeProductsSection\getACFLayout(),
                    Components\HomeWhy15Five\getACFLayout(),
                    Components\HorizontalCTA\getACFLayout(),
                    Components\HorizontalHero\getACFLayout(),
                    Components\HowItWorks\getACFLayout(),
                    Components\IconButtons\getACFLayout(),
                    Components\Iframe\getACFLayout(),
                    Components\ImageCheckmarkCard\getACFLayout(),
                    Components\ImageTitleImage\getACFLayout(),
                    Components\IntegrationsCards\getACFLayout(),
                    Components\InTheNews\getACFLayout(),
                    Components\MasonryGallery\getACFLayout(),
                    Components\MicrositeAgenda\getACFLayout(),
                    Components\MicrositeHero\getACFLayout(),
                    Components\NewsletterBanner\getACFLayout(),
                    Components\NewsTabs\getACFLayout(),
                    Components\Offices\getACFLayout(),
                    Components\PlansPricing\getACFLayout(),
                    Components\PlansPricingFeaturesList\getACFLayout(),
                    Components\PlansPricingNew\getACFLayout(),
                    Components\PodcastGuests\getACFLayout(),
                    Components\PodcastHosts\getACFLayout(),
                    Components\PodcastsHero\getACFLayout(),
                    Components\ProductFeatureChecklist\getACFLayout(),
                    Components\ProductFeatureContentLibrary\getACFLayout(),
                    Components\ProductFeatureHero\getACFLayout(),
                    Components\ProductFeatureTabs\getACFLayout(),
                    Components\PromotionalCard\getACFLayout(),
                    Components\QuoteColoredNumbers\getACFLayout(),
                    Components\SingleEventBlock\getACFLayout(),
                    Components\SolutionsHeroBox\getACFLayout(),
                    Components\Spacer\getACFLayout(),
                    Components\Team\getACFLayout(),
                    Components\Testimonial\getACFLayout(),
                    Components\TextImage\getACFLayout(),
                    Components\TextImageBigCTA\getACFLayout(),
                    Components\TextImageButton\getACFLayout(),
                    Components\TextImageFloatingBar\getACFLayout(),
                    Components\TextImageFramed\getACFLayout(),
                    Components\TextImageSmallCTA\getACFLayout(),
                    Components\TitleAndTwoColumns\getACFLayout(),
                    Components\TransformPricing\getACFLayout(),
                    Components\TwoColumnResourceLinks\getACFLayout(),
                    Components\TwoColumnTextSection\getACFLayout(),
                    Components\TwoColumnTextSection\getACFLayout(),
                    Components\TwoVideoSection\getACFLayout(),
                    Components\ThreeColumnHero\getACFLayout(),
                    Components\ValuesBenefits\getACFLayout(),
                    Components\VideoHero\getACFLayout(),
                    Components\VideoPopupText\getACFLayout(),
                    Components\Why15FiveHero\getACFLayout(),
                    Components\WYSIWYG\getACFLayout(),
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/page-secondary-navigation.php',
                ],
            ],
        ],
    ]);
});
