<?php

/**
 * Content Library related fields
 */

use Flynt\Utils\Options;
use ACFLayouts\Image;
use ACFLayouts\Video;

/**
 * Adds featured image to author taxonomy
 *
 */
acf_add_local_field_group([
    'key' => 'content_author_image',
    'title' => __('Featured image', 'flynt'),
    'fields' => [
        [
            'key' => 'content_author_image_group',
            'label' => __('Image', 'flynt'),
            'name' => 'image',
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'key' => 'content_author_image_desktop',
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'content_author_image_desktop_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'content_author_image_desktop_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 1,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'content_author_image_desktop_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'content_author_image_desktop_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'content_author_image_desktop_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'content_author_image_desktop_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
                [
                    'key' => 'content_author_image_mobile',
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'content_author_image_mobile_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'content_author_image_mobile_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'content_author_image_mobile_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'content_author_image_mobile_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'content_author_image_mobile_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'content_author_image_mobile_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'content-author',
            ],
        ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
]);

/**
 * Adds the advanced image field to post
 *
 */
acf_add_local_field_group([
    'key' => 'content_post_image',
    'title' => __('Featured Image', 'flynt'),
    'fields' => [
        // TODO Implement the Flynt\Components\Objects\Image here (but this one doesn't include is_lazy property)
        [
            'key' => 'featured_image',
            'label' => __('Image', 'flynt'),
            'name' => 'image',
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'key' => 'featured_image_desktop',
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'table',
                    'sub_fields' => [
                        [
                            'key' => 'featured_image_desktop_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'featured_image_desktop_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 1,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'featured_image_desktop_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'featured_image_desktop_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'featured_image_desktop_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'featured_image_desktop_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
                [
                    'key' => 'featured_image_mobile',
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'table',
                    'sub_fields' => [
                        [
                            'key' => 'featured_image_mobile_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'featured_image_mobile_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'featured_image_mobile_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'featured_image_mobile_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'featured_image_mobile_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'featured_image_mobile_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'content',
            ],
        ],
    ],
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
]);

/**
 * Adds Gravity Forms field to Gated Download template
 *
 */
acf_add_local_field_group([
    'key' => 'gated_download_gravity_form_field_group_key',
    'title' => __('Gravity Form', 'flynt'),
    'fields' => [
        [
            'key' => 'gravity_form_icon_key',
            'label' => __('SVG Icon', 'flynt'),
            'name' => 'gravity_form_icon',
            'type' => 'image',
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'max_size' => 0.1,
            'required' => 0,
            'mime_types' => 'svg',
        ],
        [
            'key' => 'gated_download_gravity_form_title_key',
            'label' => __('Title', 'flynt'),
            'name' => 'gravity_form_title',
            'type' => 'text',
            'required' => 1,
            'default_value' => __('Where should we send it?', 'flynt'),
        ],
        [
            'key' => 'gated_download_gravity_form_key',
            'label' => __('Form', 'flynt'),
            'name' => 'gravity_form',
            'type' => 'forms',
            'required' => 1,
            'return_format' => 'post_object',
            'allow_null' => 0,
            'multiple' => 0,
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'content',
            ],
            [
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'page-templates/page-content-gated-download.php',
            ],
        ],
    ],
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
]);

/**
 * Adds Video fields to Gated Video template
 *
 */
acf_add_local_field_group([
    'title' => __('Video Settings', 'flynt'),
    'fields' => [
        [
            'key' => 'gated_video_video_group',
            'label' => __('Video', 'flynt'),
            'name' => 'video',
            'type' => 'group',
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key' => 'gated_video_video_source',
                    'label' => __('Video Source', 'flynt'),
                    'name' => 'video_source',
                    'type' => 'radio',
                    'instructions' => __(
                        'Choose if the video is hosted on another platform and you wish to embed an iFrame or if the 
                        video is hosted in the WordPress uploads',
                        'flynt'
                    ),
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'layout' => 'horizontal',
                    'choices' => [
                        'wistia' => __('Wistia Video ID (Lazyloaded)', 'flynt'),
                        'iframe' => __('iFrame', 'flynt'),
                        'self' => __('Self-hosted', 'flynt'),
                    ],
                    'default_value' => 'iframe',
                ],
                [
                    'key' => 'gated_video_video_file',
                    'label' => __('Video file', 'flynt'),
                    'name' => 'video_file',
                    'type' => 'file',
                    'return_format' => 'url',
                    'library' => 'all',
                    'mime_types' => 'mp4,mpeg4',
                    'required' => true,
                    'conditional_logic' => [
                        [
                            [
                                'fieldPath' => 'video_source',
                                'operator' => '==',
                                'value' => 'self',
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'gated_video_video_captions',
                    'label' => __('Self-Hosted Video Captions', 'flynt'),
                    'name' => 'video_captions',
                    'type' => 'repeater',
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Captions File',
                    'sub_fields' => [
                        [
                            'label' => __('VTT Captions File', 'flynt'),
                            'name' => 'vtt_file',
                            'type' => 'file',
                            'return_format' => 'url',
                            'library' => 'all',
                            'mime_types' => 'vtt',
                        ],
                        [
                            'label' => __('Language', 'flynt'),
                            'name' => 'lang',
                            'type' => 'text',
                            'instructions' => __(
                                'Type a language code according to the ISO 639-1 standard (eg. es, en, pt)',
                                'flynt'
                            ),
                        ],
                        [
                            'label' => __('File Label', 'flynt'),
                            'name' => 'file_label',
                            'type' => 'text',
                        ],
                    ],
                    'conditional_logic' => [
                        [
                            [
                                'fieldPath' => 'video_source',
                                'operator' => '==',
                                'value' => 'self',
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'gated_video_video_embed',
                    'label' => __('Embed code from video platform', 'flynt'),
                    'name' => 'iframe_code',
                    'type' => 'textarea',
                    'rows' => 8,
                    'required' => true,
                    'conditional_logic' => [
                        [
                            [
                                'fieldPath' => 'video_source',
                                'operator' => '==',
                                'value' => 'iframe',
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'gated_video_video_wistia_id',
                    'label' => __('Wistia Video ID'),
                    'name' => 'wistia_id',
                    'type' => 'text',
                    'conditional_logic' => [
                        [
                            [
                                'fieldPath' => 'video_source',
                                'operator' => '==',
                                'value' => 'wistia',
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'gated_video_tooltip_message',
                    'label' => 'Locked video tooltip message',
                    'name' => 'video_tooltip',
                    'type' => 'text',
                    'default_value' => __('Please fill out the form to view the video', 'flynt'),
                ],
                [
                    'key' => 'gated_video_tooltip_message_mobile',
                    'label' => 'Locked Video Mobile Button message',
                    'name' => 'video_tooltip_mobile',
                    'type' => 'text',
                    'default_value' => __('Complete Form to Watch Now', 'flynt'),
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'content',
            ],
            [
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'page-templates/page-content-gated-video.php',
            ],
        ],
    ],
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
]);

/**
 * Adds Gravity Forms field to Gated Video template
 *
 */
acf_add_local_field_group([
    'title' => __('Gravity Form', 'flynt'),
    'fields' => [
        [
            'key' => 'gated_video_gravity_form_title_key',
            'label' => __('Title', 'flynt'),
            'name' => 'gravity_form_title',
            'type' => 'text',
            'required' => 1,
            'default_value' => __('Register to watch this recording on-demand.', 'flynt'),
        ],
        [
            'key' => 'gated_video_gravity_form_key',
            'label' => __('Form', 'flynt'),
            'name' => 'gravity_form',
            'type' => 'forms',
            'required' => 1,
            'return_format' => 'id',
            'allow_null' => 0,
            'multiple' => 0,
        ],
        [
            'key' => 'gated_video_already_user',
            'label' => '"Already have an account" message',
            'name' => 'already_user_message',
            'type' => 'group',
            'sub_fields' => [
                [
                    'key' => 'gated_video_already_user_message',
                    'label' => 'Message',
                    'name' => 'text',
                    'type' => 'text',
                    'default_value' => __('Already have an account?', 'flynt'),
                ],
                [
                    'key' => 'gated_video_already_user_button',
                    'label' => 'Button',
                    'name' => 'button',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
            ],
        ],
        [
            'key' => 'gated_video_gravity_form_sucess_tooltip',
            'label' => 'Form sucess tooltip message',
            'name' => 'form_success_tooltip',
            'type' => 'text',
            'default_value' => __(
                '🎉 Thanks for registering! We hope you enjoy the video.',
                'flynt'
            ),
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'content',
            ],
            [
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'page-templates/page-content-gated-video.php',
            ],
        ],
    ],
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
]);

/**
 * Adds disclosure notice after the form submit button
 *
 */
add_filter(
    'gform_submit_button',
    function ($button, $form) {
        $disclosure = Options::getGlobal('Form Settings', 'gravity_form_disclosure');
        return $button .= '<div class="disclosure">' . $disclosure . '</div>';
    },
    10,
    2
);

/**
 * Adds Thank You page featured post
 *
 */
acf_add_local_field_group([
    'key' => 'thank_you_page_field_group_key',
    'title' => __('Thank You Page', 'flynt'),
    'fields' => [
        [
            'key' => 'thank_you_page_featured_post_key',
            'label' => __('Featured Post', 'flynt'),
            'name' => 'thank_you_page_featured_post',
            'type' => 'post_object',
            'post_type' => 'content',
            'return_format' => 'object',
            'required' => true,
        ],
        // TODO Implement the Flynt\Components\Objects\Image here (but this one doesn't include is_lazy property)
        [
            'key' => 'thank_you_page_image_key',
            'label' => __('Image', 'flynt'),
            'name' => 'thank_you_page_image',
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'key' => 'thank_you_page_image_desktop_key',
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'table',
                    'sub_fields' => [
                        [
                            'key' => 'thank_you_page_image_desktop_one_x_key',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'thank_you_page_image_desktop_one_x_old_format_key',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'thank_you_page_image_desktop_one_x_avif_key',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'thank_you_page_image_desktop_two_x_key',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'thank_you_page_image_desktop_two_x_old_format_key',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'thank_you_page_image_desktop_two_x_avif_key',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
                [
                    'key' => 'thank_you_page_image_mobile_key',
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'table',
                    'sub_fields' => [
                        [
                            'key' => 'thank_you_page_image_mobile_one_x_key',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'thank_you_page_image_mobile_one_x_old_format_key',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'thank_you_page_image_mobile_one_x_avif_key',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'thank_you_page_image_mobile_two_x_key',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'thank_you_page_image_mobile_two_x_old_format_key',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'thank_you_page_image_mobile_two_x_avif_key',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '2',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
            ],
        ],
        [
            'key' => 'thank_you_page_title_key',
            'label' => __('Title', 'flynt'),
            'name' => 'thank_you_page_title',
            'type' => 'text',
            'required' => 0,
        ],
        [
            'key' => 'thank_you_page_description_key',
            'label' => __('Description', 'flynt'),
            'name' => 'thank_you_page_description',
            'type' => 'wysiwyg',
            'required' => 0,
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'content',
            ],
            [
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'page-templates/page-content-gated-download.php',
            ],
        ],
    ],
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
]);
