<?php

acf_add_local_field_group([
    'key' => 'events_featured_image',
    'name' => 'eventsFeaturedImages',
    'title' => 'Event Details',
    'style' => 'standard',
    'position' => 'normal',
    'fields' => [
        [
            'key' => 'event_featured_image_group',
            'label' => __('Featured Image', 'flynt'),
            'name' => 'events_featured_image',
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'key' => 'event_featured_image_desktop',
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'event_featured_image_desktop_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_featured_image_desktop_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 1,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_featured_image_desktop_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'event_featured_image_desktop_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_featured_image_desktop_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_featured_image_desktop_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
                [
                    'key' => 'event_featured_image_mobile',
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'event_featured_image_mobile_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_featured_image_mobile_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_featured_image_mobile_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'event_featured_image_mobile_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_featured_image_mobile_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_featured_image_mobile_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ],
        ],
    ],
]);

acf_add_local_field_group([
    'key' => 'events_fields',
    'name' => 'eventsComponents',
    'title' => 'Event Details',
    'style' => 'standard',
    'position' => 'normal',
    'fields' => [
        [
            'key' => 'event_image_group',
            'label' => __('Image', 'flynt'),
            'name' => 'events_image',
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'key' => 'event_image_desktop',
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'event_image_desktop_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_image_desktop_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 1,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_image_desktop_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'event_image_desktop_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_image_desktop_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_image_desktop_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
                [
                    'key' => 'event_image_mobile',
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'event_image_mobile_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_image_mobile_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_image_mobile_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'event_image_mobile_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' => 'event_image_mobile_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_image_mobile_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
            ],
        ],
        [
            'key' => 'events_url',
            'label' => __('Event URL', 'flynt'),
            'name' => 'url',
            'type' => 'url',
            'required' => 1,
        ],
        [
            'key' => 'events_s_date',
            'label' => __('Event Start Date', 'flynt'),
            'name' => 'event_start_date',
            'type' => 'date_picker',
            'display_format' => 'm/d/Y',
            'return_format' => 'F j, Y',
            'first_day' => 1,
            'required' => 1,
        ],
        [
            'key' => 'events_e_date',
            'label' => __('Event End Date', 'flynt'),
            'name' => 'event_end_date',
            'type' => 'date_picker',
            'display_format' => 'm/d/Y',
            'return_format' => 'F j, Y',
            'first_day' => 1,
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ],
        ],
    ],
]);

acf_add_local_field_group([
    'key' => 'events_on_demand_featured_image',
    'name' => 'eventsOnDemandFeaturedImages',
    'title' => 'Events Featured Image',
    'style' => 'standard',
    'position' => 'normal',
    'fields' => [
        [
            'key' => 'event_on_demand_featured_image_group',
            'label' => __('Events Featured Image', 'flynt'),
            'name' => 'events_on_demand_featured_image',
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'key' => 'event_on_demand_featured_image_desktop',
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'event_on_demand_featured_image_desktop_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' =>
                                        'event_on_demand_featured_image_desktop_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_on_demand_featured_image_desktop_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'event_on_demand_featured_image_desktop_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' =>
                                        'event_on_demand_featured_image_desktop_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_on_demand_featured_image_desktop_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
                [
                    'key' => 'event_on_demand_featured_image_mobile',
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'event_on_demand_featured_image_mobile_one_x',
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' =>
                                        'event_on_demand_featured_image_mobile_one_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_on_demand_featured_image_mobile_one_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                        [
                            'key' => 'event_on_demand_featured_image_mobile_two_x',
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'key' =>
                                        'event_on_demand_featured_image_mobile_two_x_old_format',
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                [
                                    'key' => 'event_on_demand_featured_image_mobile_two_x_avif',
                                    'label' => __('AVIF', 'flynt'),
                                    'name' => 'avif',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'avif',
                                ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'content',
            ],
            [
                'param' => 'post_taxonomy',
                'operator' => '==',
                'value' => 'content-type:on-demand',
            ],
        ],
    ],
]);
