<?php

namespace ACFLayouts;

class Image
{
    public static function getACFLayout(
        string $image_label = 'Image',
        string $image_name = 'image',
        bool $image_required = true
    ) {
        return [
            'label' => __($image_label, 'flynt'),
            'name' => $image_name,
            'type' => 'group',
            'layout' => 'block',
            'required' => 0,
            'sub_fields' => [
                [
                    'label' => __('Lazyload', 'flynt'),
                    'name' => 'is_lazy',
                    'type' => 'true_false',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => __('Yes', 'flynt'),
                    'ui_off_text' => __('No', 'flynt'),
                ],
                [
                    'label' => __('Desktop', 'flynt'),
                    'name' => 'desktop',
                    'type' => 'group',
                    'layout' => 'table',
                    'sub_fields' => [
                        [
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => $image_required,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                // [
                                //     'label' => __('AVIF', 'flynt'),
                                //     'name' => 'avif',
                                //     'type' => 'image',
                                //     'required' => 0,
                                //     'preview_size' => 'thumbnail',
                                //     'return_format' => 'array',
                                //     'library' => 'all',
                                //     'min_width' => 0,
                                //     'min_height' => 0,
                                //     'min_size' => 0,
                                //     'max_width' => 2000,
                                //     'max_height' => '',
                                //     'max_size' => '1',
                                //     'mime_types' => 'avif',
                                // ],
                            ],
                        ],
                        [
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 4000,
                                    'max_height' => '',
                                    'max_size' => '3',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                // [
                                //     'label' => __('AVIF', 'flynt'),
                                //     'name' => 'avif',
                                //     'type' => 'image',
                                //     'required' => 0,
                                //     'preview_size' => 'thumbnail',
                                //     'return_format' => 'array',
                                //     'library' => 'all',
                                //     'min_width' => 0,
                                //     'min_height' => 0,
                                //     'min_size' => 0,
                                //     'max_width' => 4000,
                                //     'max_height' => '',
                                //     'max_size' => '3',
                                //     'mime_types' => 'avif',
                                // ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '100',
                    ],
                ],
                [
                    'label' => __('Mobile', 'flynt'),
                    'name' => 'mobile',
                    'type' => 'group',
                    'layout' => 'table',
                    'sub_fields' => [
                        [
                            'label' => __('@1x', 'flynt'),
                            'name' => 'one_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 1000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                // [
                                //     'label' => __('AVIF', 'flynt'),
                                //     'name' => 'avif',
                                //     'type' => 'image',
                                //     'required' => 0,
                                //     'preview_size' => 'thumbnail',
                                //     'return_format' => 'array',
                                //     'library' => 'all',
                                //     'min_width' => 0,
                                //     'min_height' => 0,
                                //     'min_size' => 0,
                                //     'max_width' => 1000,
                                //     'max_height' => '',
                                //     'max_size' => '1',
                                //     'mime_types' => 'avif',
                                // ],
                            ],
                        ],
                        [
                            'label' => __('@2x', 'flynt'),
                            'name' => 'two_x',
                            'type' => 'group',
                            'layout' => 'table',
                            'sub_fields' => [
                                [
                                    'label' => __('PNG/JPEG/SVG', 'flynt'),
                                    'name' => 'old_format',
                                    'type' => 'image',
                                    'required' => 0,
                                    'preview_size' => 'thumbnail',
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => 0,
                                    'min_height' => 0,
                                    'min_size' => 0,
                                    'max_width' => 2000,
                                    'max_height' => '',
                                    'max_size' => '1',
                                    'mime_types' => 'png,jpg,jpeg,svg',
                                ],
                                // [
                                //     'label' => __('AVIF', 'flynt'),
                                //     'name' => 'avif',
                                //     'type' => 'image',
                                //     'required' => 0,
                                //     'preview_size' => 'thumbnail',
                                //     'return_format' => 'array',
                                //     'library' => 'all',
                                //     'min_width' => 0,
                                //     'min_height' => 0,
                                //     'min_size' => 0,
                                //     'max_width' => 2000,
                                //     'max_height' => '',
                                //     'max_size' => '1',
                                //     'mime_types' => 'avif',
                                // ],
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '100',
                    ],
                ],
            ],
        ];
    }
}
